name: devgiglio-access-control

services:
  access-control:
    image: ghcr.io/gipierogiglio-prog/access-control:latest
    container_name: devgiglio-access-panel
    restart: always
    ports:
      - "3001:3001"
    networks:
      - devgiglio-network
    environment:
      - PORT=3001

networks:
  devgiglio-network:
    external: true
